-- Auto generated by post.py, do not edit
return {
    ["subspace-item-extractor"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/item/item-extractor-hr-animation-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
            },
            {
                filename = "__subspace_storage__/graphics/entity/item/item-extractor-hr-shadow.png",
                width = 1000,
                height = 666,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_shadow = true,
            },
            {
                filename = "__subspace_storage__/graphics/entity/item/item-extractor-hr-emission-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_glow = true,
                blend_mode = "additive",
            }
        },
    },
    ["subspace-item-injector"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/item/item-extractor-hr-animation-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
            },
            {
                filename = "__subspace_storage__/graphics/entity/item/item-extractor-hr-shadow.png",
                width = 1000,
                height = 666,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_shadow = true,
            },
            {
                filename = "__subspace_storage__/graphics/entity/item/item-extractor-hr-emission-1-grayscale.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_glow = true,
                blend_mode = "additive",
                tint = { r = 1, g = 0, b = 1, a = 1 },
            }
        },
    },
    ["subspace-fluid-extractor"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/fluid/fluid-extractor-hr-animation-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
            },
            {
                filename = "__subspace_storage__/graphics/entity/fluid/fluid-extractor-hr-shadow.png",
                width = 1000,
                height = 666,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_shadow = true,
            },
            {
                filename = "__subspace_storage__/graphics/entity/fluid/fluid-extractor-hr-emission-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_glow = true,
                blend_mode = "additive",
            }
        },
    },
    ["subspace-fluid-injector"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/fluid/fluid-extractor-hr-animation-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
            },
            {
                filename = "__subspace_storage__/graphics/entity/fluid/fluid-extractor-hr-shadow.png",
                width = 1000,
                height = 666,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_shadow = true,
            },
            {
                filename = "__subspace_storage__/graphics/entity/fluid/fluid-extractor-hr-emission-1-grayscale.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_glow = true,
                blend_mode = "additive",
                tint = { r = 1, g = 0, b = 1, a = 1 },
            }
        },
    },
    ["subspace-electricity-extractor"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/electricity/electricity-extractor-hr-animation-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
            },
            {
                filename = "__subspace_storage__/graphics/entity/electricity/electricity-extractor-hr-shadow.png",
                width = 1000,
                height = 666,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_shadow = true,
            },
            {
                filename = "__subspace_storage__/graphics/entity/electricity/electricity-extractor-hr-emission-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_glow = true,
                blend_mode = "additive",
            }
        },
    },
    ["subspace-electricity-injector"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/electricity/electricity-extractor-hr-animation-1.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
            },
            {
                filename = "__subspace_storage__/graphics/entity/electricity/electricity-extractor-hr-shadow.png",
                width = 1000,
                height = 666,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_shadow = true,
            },
            {
                filename = "__subspace_storage__/graphics/entity/electricity/electricity-extractor-hr-emission-1-grayscale.png",
                width = 530,
                height = 530,
                shift = util.by_pixel_hr(0.0, 0),
                scale = 0.5,
                draw_as_glow = true,
                blend_mode = "additive",
                tint = { r = 1, g = 0, b = 1, a = 1 },
            }
        },
    },
}
