-- Auto generated by post.py, do not edit
return {
    ["subspace-item-extractor"] = "__subspace_storage__/graphics/icons/item-extractor-icon.png",
    ["subspace-item-injector"] = "__subspace_storage__/graphics/icons/item-injector.png",
    ["subspace-fluid-extractor"] = "__subspace_storage__/graphics/icons/fluid-extractor.png",
    ["subspace-fluid-injector"] = "__subspace_storage__/graphics/icons/fluid-injector.png",
    ["subspace-electricity-extractor"] = "__subspace_storage__/graphics/icons/electricity-extractor.png",
    ["subspace-electricity-injector"] = "__subspace_storage__/graphics/icons/electricity-injector.png",
}
