-- Auto generated by post.py, do not edit
return {
    ["subspace-item-extractor"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/item-extractor.png",
                width = 254,
                height = 242,
                shift = util.by_pixel(0.0, 1.0),
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/item-extractor-hr.png",
                    width = 506,
                    height = 483,
                    shift = util.by_pixel_hr(0.0, 1.5),
                    scale = 0.5,
                },
            },
            {
                filename = "__subspace_storage__/graphics/entity/item-shadow.png",
                width = 111,
                height = 201,
                shift = util.by_pixel(176.5, 20.5),
                draw_as_shadow = true,
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/item-shadow-hr.png",
                    width = 222,
                    height = 401,
                    shift = util.by_pixel_hr(354.0, 41.5),
                    scale = 0.5,
                    draw_as_shadow = true,
                },
            },
        },
    },
    ["subspace-item-injector"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/item-injector.png",
                width = 254,
                height = 242,
                shift = util.by_pixel(0.0, 1.0),
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/item-injector-hr.png",
                    width = 506,
                    height = 483,
                    shift = util.by_pixel_hr(0.0, 1.5),
                    scale = 0.5,
                },
            },
            {
                filename = "__subspace_storage__/graphics/entity/item-shadow.png",
                width = 111,
                height = 201,
                shift = util.by_pixel(176.5, 20.5),
                draw_as_shadow = true,
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/item-shadow-hr.png",
                    width = 222,
                    height = 401,
                    shift = util.by_pixel_hr(354.0, 41.5),
                    scale = 0.5,
                    draw_as_shadow = true,
                },
            },
        },
    },
    ["subspace-fluid-extractor"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/fluid-extractor.png",
                width = 256,
                height = 268,
                shift = util.by_pixel(0.0, 0.0),
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/fluid-extractor-hr.png",
                    width = 512,
                    height = 534,
                    shift = util.by_pixel_hr(0.0, 0.0),
                    scale = 0.5,
                },
            },
            {
                filename = "__subspace_storage__/graphics/entity/fluid-shadow.png",
                width = 354,
                height = 226,
                shift = util.by_pixel(55.0, 25.0),
                draw_as_shadow = true,
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/fluid-shadow-hr.png",
                    width = 708,
                    height = 453,
                    shift = util.by_pixel_hr(111.0, 50.5),
                    scale = 0.5,
                    draw_as_shadow = true,
                },
            },
        },
    },
    ["subspace-fluid-injector"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/fluid-injector.png",
                width = 256,
                height = 268,
                shift = util.by_pixel(0.0, 0.0),
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/fluid-injector-hr.png",
                    width = 512,
                    height = 534,
                    shift = util.by_pixel_hr(0.0, 0.0),
                    scale = 0.5,
                },
            },
            {
                filename = "__subspace_storage__/graphics/entity/fluid-shadow.png",
                width = 354,
                height = 226,
                shift = util.by_pixel(55.0, 25.0),
                draw_as_shadow = true,
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/fluid-shadow-hr.png",
                    width = 708,
                    height = 453,
                    shift = util.by_pixel_hr(111.0, 50.5),
                    scale = 0.5,
                    draw_as_shadow = true,
                },
            },
        },
    },
    ["subspace-electricity-extractor"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/electricity-extractor.png",
                width = 256,
                height = 251,
                shift = util.by_pixel(0.0, 1.5),
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/electricity-extractor-hr.png",
                    width = 512,
                    height = 502,
                    shift = util.by_pixel_hr(0.0, 3.0),
                    scale = 0.5,
                },
            },
            {
                filename = "__subspace_storage__/graphics/entity/electricity-shadow.png",
                width = 345,
                height = 229,
                shift = util.by_pixel(59.5, 12.5),
                draw_as_shadow = true,
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/electricity-shadow-hr.png",
                    width = 693,
                    height = 457,
                    shift = util.by_pixel_hr(118.5, 25.5),
                    scale = 0.5,
                    draw_as_shadow = true,
                },
            },
        },
    },
    ["subspace-electricity-injector"] = {
        layers = {
            {
                filename = "__subspace_storage__/graphics/entity/electricity-injector.png",
                width = 256,
                height = 251,
                shift = util.by_pixel(0.0, 1.5),
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/electricity-injector-hr.png",
                    width = 512,
                    height = 502,
                    shift = util.by_pixel_hr(0.0, 3.0),
                    scale = 0.5,
                },
            },
            {
                filename = "__subspace_storage__/graphics/entity/electricity-shadow.png",
                width = 345,
                height = 229,
                shift = util.by_pixel(59.5, 12.5),
                draw_as_shadow = true,
                hr_version = {
                    filename = "__subspace_storage__/graphics/entity/electricity-shadow-hr.png",
                    width = 693,
                    height = 457,
                    shift = util.by_pixel_hr(118.5, 25.5),
                    scale = 0.5,
                    draw_as_shadow = true,
                },
            },
        },
    },
}
