CRAFTING_FLUID_CATEGORY_NAME = "crafting-fluids"

--item name that electricity uses
ELECTRICITY_ITEM_NAME = "electricity"
ELECTRICITY_RATIO = 1000000 -- 1.000.000,  1 = 1MJ

INV_COMBINATOR_NAME = "subspace-resource-combinator"

MAX_FLUID_AMOUNT = 25000
TICKS_TO_COLLECT_REQUESTS = 40
TICKS_TO_FULFILL_REQUESTS = 20
TICKS_TO_COLLECT_AND_FULFILL_REQUESTS = TICKS_TO_COLLECT_REQUESTS + TICKS_TO_FULFILL_REQUESTS
