# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: pnpm i --no-frozen-lockfile
    - run: node build.js
    # Upload build to artifacts
    - name: Upload build to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: subspace_storage
        path: ./dist
        if-no-files-found: error
